//
// Created by asterisk on 2022/2/24.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1 */

#ifndef _Included_com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
#define _Included_com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
 * Method:    adapterNativeHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_extension_1sdk_1demo_ExtensionSdkDemoAdapterJNI1_adapterNativeHello
        (JNIEnv *, jobject) {

}

/*
 * Class:     com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
 * Method:    adapterNativeSendMessage
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_extension_1sdk_1demo_ExtensionSdkDemoAdapterJNI1_adapterNativeSendMessage
        (JNIEnv *, jobject, jint, jstring) {

}

/*
 * Class:     com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
 * Method:    adapterNativeSendMessageWithJson
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_extension_1sdk_1demo_ExtensionSdkDemoAdapterJNI1_adapterNativeSendMessageWithJson
        (JNIEnv *, jobject, jint, jstring) {

}

/*
 * Class:     com_example_extension_sdk_demo_ExtensionSdkDemoAdapterJNI1
 * Method:    adapterNativeSendMessageWithPB
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_example_extension_1sdk_1demo_ExtensionSdkDemoAdapterJNI1_adapterNativeSendMessageWithPB
        (JNIEnv *, jobject, jint, jbyteArray) {

}

#ifdef __cplusplus
}
#endif
#endif
